
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook.pipeline.tekton.dev
  labels:
    app.kubernetes.io/component: webhook
{{ include "tekton_pipelines.labels" . | indent 4 }}
    pipeline.tekton.dev/release: {{ .Chart.AppVersion | quote }}
webhooks:
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ template "tekton_pipelines.fullname". }}-webhook
        namespace: {{ .Release.Namespace }}
    failurePolicy: Fail
    sideEffects: None
    name: webhook.pipeline.tekton.dev
