---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/component: webhook
{{ include "tekton_pipelines.labels" . | indent 4 }}
    pipeline.tekton.dev/release: {{ .Chart.AppVersion | quote }}
    app: tekton-pipelines-webhook
    version: {{ .Chart.AppVersion | quote }}
  name: {{ template "tekton_pipelines.fullname". }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
{{ .Values.webhook_service.ports | toYaml | indent 4 }}
  selector:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/component: webhook
{{ include "tekton_pipelines.labels" . | indent 4 }}

